//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieManagementApplication.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class movie_cast
    {
        public int act_id { get; set; }
        public int mov_id { get; set; }
        public string role { get; set; }
    
        public virtual actor actor { get; set; }
        public virtual movie movie { get; set; }
    }
}
