//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieManagementApplication.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class rating
    {
        public int mov_id { get; set; }
        public int rev_id { get; set; }
        public Nullable<int> rev_stars { get; set; }
        public Nullable<int> num_o_ratings { get; set; }
    
        public virtual movie movie { get; set; }
        public virtual reviewer reviewer { get; set; }
    }
}
